import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header.js";
import Footer from "@/components/Footer.js";

export default function Home() {
  const [text, setText] = useState("");
  const [aiOutput, setAiOutput] = useState("");

  const handleSummarize = async () => {
    try {
      const res = await fetch("http://localhost:5000/api/generate-notes", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ text }),
      });

      const data = await res.json();
      setAiOutput(data.output);
    } catch (err) {
      console.error(err);
      setAiOutput("Error: Could not get summary.");
    }
  };

  return (
    <>
      <Head>
        <title>ChapterWise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <p>Paste your textbook chapter in the box below.</p>
        <p>
          Click ‘Generate Notes’ to get exam-ready study notes formatted with
          key sections.
        </p>
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Paste your chapter here…"
        ></textarea>
        {/* character count */}
        {/* Validation: check text length, prevent empty submission. */}
        {/* file upload (PDF, DOCX) support. */}
        <button onClick={handleSummarize}>Generate Notes</button>
        {/* Disabled while AI is processing */}
        {/* Show a spinner or “Generating notes…” message while API call is in progress. */}
        {/* Error message handling (e.g., network errors, API errors). */}
        <pre>
          {aiOutput || "Output will appear here..."}
        </pre>
      </main>
      <Footer />
    </>
  );
}
